name: ${pluginName}
version: '${pluginVersion}'
main: ${pluginMain}
description: ${pluginDescription}
author: ${pluginAuthor}

api-version: '1.20'
folia-supported: true

permissions:
  shulker.admin:
    default: op
